Use dist: focal on Travis
Fixes

  RuntimeError: You are linking against OpenSSL 1.0.2, which is no longer supported by the OpenSSL project. To use this version of cryptography you need to upgrade to a newer version of OpenSSL. For this version only you can also set the environment variable CRYPTOGRAPHY_ALLOW_OPENSSL_102 to allow OpenSSL 1.0.2.

during pip install cryptography in python: pypy builds.

NB: dist: bionic/focal do not have python: pypy but do have pypy2.